name: remote ssh command
on: 
 push:
  branches:
    - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_IOT_HOST }}
        username: ${{ secrets.EC2_IOT_USERNAME }}
        key: ${{ secrets.EC2_IOT_KEY }}
        port: 22
        script: bash /home/ubuntu/IoTPlatform/deploy_iot.sh
